language: java
jdk:
  - oraclejdk7

install: true
script:
  - "cd modules;mvn clean test"
  - jdk_switcher use oraclejdk8 
  - "mvn clean test"
  - mvn clean package -Dmaven.test.skip=true
  - jdk_switcher use oraclejdk7
  - "mvn test"
  - "mvn clean package -Dmaven.test.skip=true" 
  - jdk_switcher use oraclejdk7
  - "mvn test"  

branches:
  only:
    - master 
before_install:
  - wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
